export const DOCUMENTATION_URL = 'https://docs.modx.com/current/{lang}/building-sites/resources';

export default [
  'id',
  'pagetitle',
  'isfolder',
  'longtitle',
  'description',
  'alias',
  'published',
  'introtext',
  'content',
  'template',
  'menutitle',
  'hidemenu',
  'parent',
  'menuindex',
  'searchable',
  'cacheable',
  'createdby',
  'editedby',
  'deleted',
  'deletedby',
  'publishedby',
  'createdon',
  'publishedon',
  'editedon',
  'deletedon',
];
